// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proiect_Magazin_Mobila.Data;

#nullable disable

namespace Proiect_Magazin_Mobila.Migrations
{
    [DbContext(typeof(Proiect_Magazin_MobilaContext))]
    [Migration("20230106201139_categories")]
    partial class categories
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Proiect_Magazin_Mobila.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Proiect_Magazin_Mobila.Models.Designer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Designer");
                });

            modelBuilder.Entity("Proiect_Magazin_Mobila.Models.Furniture", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<int?>("DesignerID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("DesignerID");

                    b.ToTable("Furniture");
                });

            modelBuilder.Entity("Proiect_Magazin_Mobila.Models.FurnitureMaterial", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("FurnitureID")
                        .HasColumnType("int");

                    b.Property<int>("MaterialID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FurnitureID");

                    b.HasIndex("MaterialID");

                    b.ToTable("FurnitureMaterial");
                });

            modelBuilder.Entity("Proiect_Magazin_Mobila.Models.Material", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Material");
                });

            modelBuilder.Entity("Proiect_Magazin_Mobila.Models.Furniture", b =>
                {
                    b.HasOne("Proiect_Magazin_Mobila.Models.Category", "Categories")
                        .WithMany()
                        .HasForeignKey("CategoryID");

                    b.HasOne("Proiect_Magazin_Mobila.Models.Designer", "Designer")
                        .WithMany("Furnitures")
                        .HasForeignKey("DesignerID");

                    b.Navigation("Categories");

                    b.Navigation("Designer");
                });

            modelBuilder.Entity("Proiect_Magazin_Mobila.Models.FurnitureMaterial", b =>
                {
                    b.HasOne("Proiect_Magazin_Mobila.Models.Furniture", "Furniture")
                        .WithMany("FurnitureMaterials")
                        .HasForeignKey("FurnitureID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proiect_Magazin_Mobila.Models.Material", "Material")
                        .WithMany("FurnitureMaterials")
                        .HasForeignKey("MaterialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Furniture");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Proiect_Magazin_Mobila.Models.Designer", b =>
                {
                    b.Navigation("Furnitures");
                });

            modelBuilder.Entity("Proiect_Magazin_Mobila.Models.Furniture", b =>
                {
                    b.Navigation("FurnitureMaterials");
                });

            modelBuilder.Entity("Proiect_Magazin_Mobila.Models.Material", b =>
                {
                    b.Navigation("FurnitureMaterials");
                });
#pragma warning restore 612, 618
        }
    }
}
